from firebase import FirebaseManager
import pprint

fb_man = FirebaseManager()

r3_dict, _ = fb_man.get_r3()

all_ingredients = set()

for i, r3 in r3_dict.items():
    # print(r3["recipe_name"])

    for el in r3["ingredients"]:
        if "name" not in el:
            if "ingredient_name" in el:
                el["name"] = el.pop("ingredient_name")

    all_ingredients = all_ingredients.union(
        set([el["name"] for el in r3["ingredients"]])
    )


not_vegan = {
    "softened butter",
    "Nacho Cheese",
    "salmon",
    "applewood smoked bacon",
    "eggs",
    "egg mixture",
    "milk",
    "Ground Beef",
    "sour cream",
}
glutenous = {}
high_sugar = {
    "chocolate",
    "white sugar",
    "applewood smoked bacon",
    "White Chocolate Chips",
    "sugar",
    "sprinkle for eyes",
}


{
    "vegetable oil",
    "Green Onions",
    "buttermilk",
    "ground beef chuck",
    "red chili powder",
    "parsley",
    "beef bouillon powder",
    "Yellow and Green M&M",
    "quick-cooking oatmeal",
    "dried dill weed",
    "mayonnaise",
    "taco shells",
    "cheddar cheese",
    "ground cinnamon",
    "nacho cheese sauce",
    "Roma tomatoes",
    "sprinkle for nose",
    "mayyonnaise",
    "brown sugar",
    "graham crackers",
    "diced tomato",
    "ground nutmeg",
    "bacon",
    "water",
    "sausage",
    "pickled jalapeno juice",
    "red onion",
    "ranch seasoning",
    "skin-on or blanched whole almonds",
    "kale strips",
    "Pickled Jalapeno Juice",
    "ginger",
    "Shredded Mexican Cheese Blend",
    "red chilli",
    "canned black beans in seasoned sauce",
    "American cheese",
    "egg white",
    "chipotle chili powder or regular chili powder",
    "heavy whipping cream",
    "allspice",
    "garlic cloves",
    "salsa or hot sauce",
    "masa harina",
    "nutmeg",
    "sprinkle for mouth",
    "shredded Mexican cheese",
    "large round tomato slices",
    "white tortillas",
    "pepper",
    "mustard",
    "whipped cream",
    "all-purpose flour",
    "shredded lettuce",
    "Big Mac sauce",
    "hass avacado",
    "sliced white onions",
    "slivered blanched almonds",
    "boneless skinless chicken breasts",
    "raisins",
    "Paprika",
    "red apple",
    "granny smith apple",
    "corn meal",
    "Granny Smith apple",
    "paprika",
    "chocolate chips",
    "crinkle-cut dill pickles",
    "food coloring",
    "Tomato",
    "Tortilla Chips",
    "ripe avocado",
    "black pepper",
    "ground beef",
    "ketchup",
    "mayo",
    "chives",
    "egg whites",
    "chicken broth",
    "Vegetable Oil",
    "Mayo",
    "Refried Beans",
    "Whipped cream",
    "juice from 1 lemon",
    "Canadian Bacon",
    "soy sauce",
    "breadcrumbs",
    "bread",
    "smoked paprika",
    "phyllo dough",
    "hamburger buns",
    "Cheddar & Monterey Jack Cheese",
    "teabags",
    "cornstarch",
    "red chilli powder",
    "Flour Tortillas",
    "mushroom",
    "salt",
    "Jell-O",
    "egg",
    "puff pastry",
    "pork sausage",
    "sesame seed hamburger buns",
    "lemon juice",
    "dried parsley",
    "salad",
    "English Muffins",
    "salad kit",
    "onion",
    "fresh tomatoes",
    "avocado",
    "garlic salt",
    "granulated sugar",
    "puff pastry sheet",
    "coriander",
    "dill pickle slices",
    "shrimp",
    "coconut",
    "asparagus",
    "capers",
    "vanilla extract",
    "hot water",
    "flour",
    "shredded cheddar cheese",
    "Melted chocolate chips & chopped walnuts",
    "all purpose flour",
    "Sour Cream",
    "Chicken Breast",
    "jalapeno pepper",
    "beef round roast",
    "bell pepper",
    "almond flour",
    "Unsalted butter",
    "plain non-fat Greek yogurt",
    "melted butter",
    "Jalapenos",
    "refried beans",
    "salsa",
    "sliced almonds",
    "scallions",
    "Craisins",
    "Hidden Valley Original Ranch Seasoning and Salad Dressing Mix",
    "onion powder",
    "ice",
    "crescent rolls",
    "vanilla",
    "Salsa or Hot Sauce",
    "hot sauce",
    "rice noodles",
    "ground cumin",
    "egg yolks",
    "butter",
    "caramel ice cream topping",
    "pecans",
    "pepper corns",
    "cinnamon",
    "tomatoes",
    "carrot",
    "pickled jalapeÃ±os",
    "vinegar",
    "minced onion",
    "dried oregano",
    "potato hamburger buns",
    "onions",
    "large eggs",
    "Gordita Flour Tortillas",
    "tomato ketchup",
    "Cayenne Pepper",
    "dried minced onion",
    "vanilla bean pod",
    "American Cheese",
    "roma tomatoes",
    "pancake mix",
    "half and half",
    "baking powder",
    "Taco sauce",
    "yellow or white onion",
    "ham",
    "Sugar",
    "white vinegar",
    "cooking spray",
    "Garlic Powder",
    "finely shredded cheese",
    "pancake syrup",
    "food color",
    "cheese",
    "Sliced almonds",
    "chicken",
    "Mini Pretzel sticks",
    "walnuts",
    "liquid smoke",
    "iceberg lettuce",
    "spinach",
    "Kawan parathas",
    "unsalted butter",
    "hot coffee",
    "red delicious apple",
    "avacado",
    "burrito sized flour tortillas",
    "cilantro",
    "corn muffin",
    "baking soda",
    "fresh lime juice",
    "pickled jalapenos",
    "avacado dip",
    "red pepper",
    "honey",
    "chili powder",
    "garlic",
    "ground chuck",
    "cumin",
    "tostadas",
    "Minced Pickled Jalapenos",
    "red pepper flakes",
    "peanut butter candy",
    "Hard Taco Shells",
    "taco seasoning mix",
    "ice water",
    "powdered sugar",
    "green chilies",
    "corriander",
    "garlic powder",
    "peanut butter",
    "sausage patties",
    "tortillas",
    "maple syrup",
    "yellow onion",
    "turmeric",
    "low-sodium pumpkin",
    "cream of tartar",
}


print(all_ingredients)
# gluten_free = input("gluten-free (y/n), y default")
# assert gluten_free in ["n", "", "y"]
# gluten_free = gluten_free != "n"

# vegan = input("vegan (y/n), y default")
# assert vegan in ["n", "", "y"]
# vegan = vegan != "n"

# low_sugar = input("low_sugar (y/n), y default")
# assert low_sugar in ["n", "", "y"]
# low_sugar = low_sugar != "n"

# r3["low_sugar"] = low_sugar
# r3["vegan"] = vegan
# r3["gluten_free"] = gluten_free

# with open(f"{r3["recipe_name"]}.json", "w") as f:
#     json.dump()
