name: Deploy to AWS EC2

on:
  pull_request:
    types:
      - closed # Runs only when a PR is closed
    branches:
      - "**" # Match all branches

jobs:
  deploy:
    if: github.event.pull_request.merged == true # Only runes if the PR is merged successfully
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Prepare SSH Key
        env:
          AWS_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        run: |
          # Ensure SSH directory exists
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Save private key and remove carriage return characters
          echo "$AWS_KEY" | tr -d '\r' > ~/.ssh/aws_ec2_key.pem
          chmod 400 ~/.ssh/aws_ec2_key.pem

          # Start SSH agent and add the key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/aws_ec2_key.pem

          # Add EC2 host to known_hosts (prevents host verification errors)
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
          
      - name: Run Deployment Commands on EC2
        env:
          AWS_HOST: ${{ secrets.AWS_HOST }}
          AWS_USER: ubuntu
        run: |
          echo "Running Deployment on EC2..."

          ssh -i ~/.ssh/aws_ec2_key.pem $AWS_USER@$AWS_HOST << 'EOF'
            set -e

            cd /home/ubuntu/beacon-of-hope/
            ./deploy.sh
            
          EOF

      - name: Cleanup SSH Key
        run: rm -f ~/.ssh/aws_ec2_key.pem
